name: Flutter CI/CD testing

on:
  push:
    branches: 
      - develop

env:
  FLUTTER_ENV_FILE: .env

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      contents: write

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.2'

    - name: Instalar dependencias
      run: flutter pub get

    - name: Crear archivo .env con URL del entorno
      run: |
        echo "POCKETBASE_URL=${{ vars.POCKETBASE_URL }}" > .env

    - name: Compular APK en modo release
      run: flutter build apk --release

    - name: Crear y pushear tag dinámico
      run: |
        TAG=testing-build-${{ github.run_number }}
        git tag $TAG
        git push origin $TAG
        
    - name: Crear Release y subir APK
      uses: softprops/action-gh-release@v1
      with:
        name: Release testing-build-${{ github.run_number }}
        tag_name: testing-build-${{ github.run_number }}
        body: |
          Versión de testing compilada desde develop
          Commit: ${{ github.sha }}
        files: build/app/outputs/flutter-apk/app-release.apk
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
