name: Flutter CI/CD testing

on:
  push:
    branches: 
     - develop

env:
  FLUTTER_ENV_FILE: .env

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3

    - name: 🏷️ Crear tag dinámico
      run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag testing-build-${{ github.run_number }}
          git push origin testing-build-${{ github.run_number }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.2'

    - name: Instalar dependencias
      run: flutter pub get

    - name: Crear archivo .env con URL del entorno
      run: |
        echo "POCKETBASE_URL=${{ vars.POCKETBASE_URL }}" > .env

    - name: Ejecutar pruebas
      run: flutter test

    - name: Compular APK en modo release
      run: flutter build apk --release

    - name: Crear Release en Github
      uses: softprops/action-gh-release@v1
      with:
        name: Release testing-build-${{ github.run_number }}
        tag_name: testing-build-${{ github.run_number }}
        body: |
          Versión de testing compilada desde develop
          Commit: ${{ github.sha }}
      env: 
        GITHUB_TOKEN: ${{  secrets.GH_PAT }}

    - name: Subir APK al Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    
